# Copy to config.py (gitignored) for local development.
# On the deployed site, config.py is generated by .github/workflows/deploy.yml
# from repository secrets - never commit real values here.

SUPABASE_URL = "https://your-project-ref.supabase.co"
SUPABASE_ANON_KEY = "your-anon-or-publishable-key"
VAPID_PUBLIC_KEY = "your-vapid-public-key"
